### ISSUE TITLE
Registration info

### ISSUE THREAD

**Issue by zk497** [SoftmedTanzania/opensrp-client-chw#152]
When viewing the registration information of an independent client, the family head, family member, or a client who is enrolled to a service, the fields for ID and leadership are empty. (Please note that this issue currently occurs when tested from the new branch `merging/master-v1`).

When viewing a family head's registration information, the surname field is empty. (This issue occurs even when tested from the default main branch)

**Comment by cozej4** [comment]
Closing this issue. As it has been fixed as of August 2022
