### ISSUE TITLE
Swahili Version - Namba ya Utambulisho

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw#192]
Namba ya utambulisho should not reflect in the first part of the registration forms

**Comment by cozej4** [comment]
@Kasika-S Please add a screenshot to show what should be removed

**Comment by Kasika-S** [comment]
![Image](https://user-images.githubusercontent.com/65092133/191242643-0f45f738-d6a5-46e6-90d1-56b9278b307a.png)

This is a bug
