### ISSUE TITLE
Mother Champion - Partner Followup

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw#214]
Once the register partner is selected and an existing partner is selected the prompt is still in english

**Comment by cozej4** [comment]
@Kasika-S Please provide the translations

**Comment by zk497** [comment]
@Kasika-S Please elaborate on this issue and provide a screenshot if possible.

**Comment by Kasika-S** [comment]
I have sent you the screenshot and the proper translation
