### ISSUE TITLE
PNC COMMUNITY-WAJA

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensrp-client-chw#226]
- [ ] When registering a client for PNC Services the **delivery date**is not limited to 42 days back like KITUONI,in WAJA the delivery date it can be years back

**Comment by cozej4** [comment]
@muyaso The current WAJA implementation checks the **Last Menstrual Period** as the minimum date for delivery date. Such that even if the mother is passed 42 days, and the mother is no longer eligible for PNC the child would still appear in the Child Module for further followup.

**_This implementation is correct_**

**Comment by muyaso** [comment]
- [ ]I get your point.....my scenario is an independent client who needs to be registered at PNC by WAJA.....so PNC is eligible for every women who have delivered at any year(and not in the window of 42 days)?

**Comment by Kasika-S** [comment]
Please limit the date picker to select only as far back as 42 days otherwise the client should not be eligible for PNC
