### ISSUE TITLE
Age mismatch on profile and register

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensrp-client-chw#300]
AGWY client home page shows the correct age of the client but once the profiles are opened they all show 52

**Comment by muyaso** [comment]
![Image](https://user-images.githubusercontent.com/107064455/194563813-b3bf60b4-71f2-49da-ae67-fdeb4baf7d57.jpg)



![Image](https://user-images.githubusercontent.com/107064455/194564069-aa37df35-9067-45c2-8b29-0d9c2f8a2ed5.png)

**Comment by Kasika-S** [comment]
This has not yet been fixed
